folder :
  software : "software" 
  res : "results"
  input : "input"
  output : "output"
params :
  gfa : "graph32.gfa"
  n_queries : "1000"
  max_length_queries : "10000"
  min_length_queries : "100"
  steps: "5"
  threads: "4"
  cache_l: "5"
